# -*- coding: utf-8 -*-
"""s1_get_stock_price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8OJI_luINrtVl3tX0-hjy8jeNHwKOFJ
"""

import requests
from bs4 import BeautifulSoup

# 종목코드 딕셔너리
stocks = {'KODEX 200커버드콜':{'code':'498400'}, 'KODEX S&P500커버드콜':{'code':'0005A0'}, 'KODEX 나스닥100커버드콜':{'code':'494300'}}

def setPrice(stocks):
    for _key, _value in stocks.items():
        url = 'https://finance.naver.com/item/main.nhn?code=' + _value['code']
        print(f'가져오실 url은 {url} 입니다')

        response = requests.get(url)
        response.raise_for_status()
        html = response.text
        soup = BeautifulSoup(html, 'html.parser')

        today = soup.select_one('#chart_area > div.rate_info > div')
        price = today.select_one('.blind')
        stocks[_key]['price']= price.get_text()
    return stocks


if __name__ == '__main__':
    stocks=setPrice(stocks)
    print(stocks)

#AttributeError: 'NoneType' object has no attribute 'select_one'
#종목코드 입력 제대로 됐는지 확인해야함

#다른 아이디어: 오늘 날씨 가져오기

#개발자 도구
## 윈도우 f12
## 맥 Option Command I

