# -*- coding: utf-8 -*-
"""s2_telegram_first.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aHkBlyL6y87G41rOY_YcitEdENMGXB2T
"""

import http.client
import json

# 본인의 토큰 값을 입력하시오
# MY_TOKEN = '111111:AAFLkKc_jA8SX9Fnlsgd_35CBVyPQ'
MY_TOKEN = '7714026092:AAHzR0oi3CBmh_-H5VoP01Tj_NJEAi82al4'

# 본인의 채팅 아이디를 입력하시오
# myChatId = 111134774
myChatId = 1298821077

# 보내고 싶은 메세지를 적어보세요
myText = '내 명령을 잘 수행해줘~ '

def tele(MY_TOKEN,myChatId,myText):
    TELEGRAM_API_HOST = 'api.telegram.org'
    connection = http.client.HTTPSConnection(TELEGRAM_API_HOST)

    # 토큰과 메서명 지정
    url = f"/bot{MY_TOKEN}/sendMessage"

    # HTTP 헤더
    headers = {'content-type': "application/json"}

    # 파라미터
    param = {
        'chat_id': myChatId,
        'text': myText
    }

    # Http 요청
    connection.request("POST", url, json.dumps(param), headers)

    # 응답
    res = connection.getresponse()

    # Response body 출력
    # print(json.dumps(json.loads(res.read().decode()), indent=4))
    print('응답코드 : ', res.status)
    try:
        assert res.status==200, "토큰값과 토큰아이디를 다시 확인해주세요"
    except AssertionError as err:
        print(err)

    # print('메시지 : ', res.msg)

    # 연결 끊기
    connection.close()

if __name__=='__main__':
    tele(MY_TOKEN,myChatId,myText)

