# -*- coding: utf-8 -*-
"""s3_telegram_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVBJ1sqTYGAiVc4eHpbBmzMBlM48ZAoV
"""

import s1_get_stock_price as getStockPrice
import s2_telegram_first as telegram


stocks = getStockPrice.setPrice(getStockPrice.stocks)
print(stocks)

text_lst = []
for _key, _value in stocks.items():
    _price = _value['price']
    text_lst.append(f'{_key} 현재가: {_price}')
# print(text_lst)
_text4tele = '\n'.join(text_lst)

telegram.tele(telegram.MY_TOKEN, telegram.myChatId, _text4tele)