# Actions -> Python application
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://crontab.guru/
# 한국 11오게하려면  cron에 11-9=2로 표현
# 한국 22 오게하려면 22-9 = 13
# 한국 오전8 오게하려면 8-9 = 23
# 한국 오전8:30 오게하려면 8-9 = 30 23
# 오전8 월-금에 오게 하려면 0 23 * * 0-4: 여기서 UTC+9 하면 1-5(월-금)이 됨


# 5분이라 걸어놓음 10분 후 쯤 15분에 알람 옴


# cron순서 - 분 시

name: Price_Bot_250524

on:
  schedule:
    - cron : 30 23 * * 0-4
  push:
    branches: [ main ]
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests==2.27.1 bs4==0.0.1

    - name: telebot
      run: |
        python s3_telegram_bot.py
